# Continuum Configuration
# Local: Continuum_Overworld (C_O) - Development
# Cloud: Continuum_Nexus (C_N) - Execution

metadata:
  local_realm: "Continuum_Overworld"
  cloud_orchestrator: "Continuum_Nexus"
  version: "2.0.0"
  playbook: "Agora/Playbook--WebDev__PROD@v2.0.0"
  
naming_conventions:
  local_prefix: "C_O"
  cloud_prefix: "C_N"
  component_pattern: "Capability--Role__Qualifier@version"
  file_pattern: "kebab-case"
  env_pattern: "SCREAMING_SNAKE_CASE"
  
aws_deployment:
  region: "us-east-1"
  environment: "PROD"
  auto_deploy: true
  risk_gate: "Aegis:T1"
  
divisions:
  - name: "The_Bridge"
    role: "Central control plane"
    cloud_name: "C_N-Bridge"
    capabilities:
      - "Helios_Console--Core__PROD"
      - "MemoryBank--API__DEV"
  
  - name: "Agora"
    role: "External interfaces"
    cloud_name: "C_N-Agora"
    capabilities:
      - "Site--GreenStemGlobal__PROD@v2.0.0"
  
  - name: "Forge"
    role: "Data processors"
    cloud_name: "C_N-Forge"
    capabilities:
      - "Ingestor--CSR__EU-DE@v1"
      - "LakeIngestor--Events__DEV"
      - "DataPlatform--DBT__DEV"
  
  - name: "Oracle"
    role: "Analytics & ML"
    cloud_name: "C_N-Oracle"
    capabilities:
      - "Calculator--ESG__PROD@v1"
      - "Forecaster--Demand__EU-Beans"
  
  - name: "Pantheon"
    role: "Agent registry"
    cloud_name: "C_N-Pantheon"
    capabilities:
      - "Registry--Agents__PROD"
  
  - name: "Atlas"
    role: "Resource mapping"
    cloud_name: "C_N-Atlas"
  
  - name: "Aegis"
    role: "Security & compliance"
    cloud_name: "C_N-Aegis"
  
  - name: "Meridian"
    role: "Navigation & routing"
    cloud_name: "C_N-Meridian"
  
  - name: "Ledger"
    role: "Blockchain integration"
    cloud_name: "C_N-Ledger"

resource_transformation:
  # DynamoDB Tables
  tables:
    "FarmMetrics": "C_N-FarmMetrics-Live"
    "TraceEvents": "C_N-TraceEvents-Stream"
    "AgentRegistry": "C_N-Pantheon-Registry"
    "OperationalMetrics": "C_N-Ops-Metrics"
  
  # EventBridge
  event_buses:
    "CoreEvents": "C_N-EventBus-Core"
    "TraceEvents": "C_N-EventBus-Trace"
  
  # Lambda Functions
  functions:
    "composer": "C_N-Composer-API"
    "admin": "C_N-Admin-API"
    "trace": "C_N-Trace-Processor"
  
  # S3 Buckets
  buckets:
    "data-lake": "c-n-data-lake-${ACCOUNT_ID}"
    "trace-archive": "c-n-trace-archive-${ACCOUNT_ID}"

branching_strategy:
  production: "main"
  staging: "stage"
  development: "dev"
  feature_prefix: "lab/"

quality_gates:
  required_checks:
    - "lint"
    - "test"
    - "verify_setup"
    - "aegis_security_scan"
  
  deployment_approval:
    - "The_Bridge"
    - "Aegis:T1"