# Production Configuration for Continuum_Overworld
# Created: 2025-01-09
# Version: 1.0.0

tenant_model:
  default: org-main
  type: single-tenant
  
region: eu-central-1

domains:
  root: greenstemglobal.com
  api:
    dev: cn-dev-api.greenstemglobal.com
    stage: cn-stage-api.greenstemglobal.com
    prod: cn-api.greenstemglobal.com
  helios:
    stage: cn-stage-helios.greenstemglobal.com
    prod: cn-helios.greenstemglobal.com
  website:
    stage: stage.greenstemglobal.com
    prod: www.greenstemglobal.com

data_retention:
  metrics: 90  # days
  events: 30   # days
  
cost_budget:
  monthly: 90  # USD
  alert_threshold: 0.8  # 80% of budget

services:
  dynamodb:
    tables:
      - C_N-Events-Trace
      - C_N-Oracle-SatelliteData
      - C_N-Oracle-WeatherData
      - C_N-Metrics-Operational
      - C_N-MetricDefinitions
    billing_mode: PAY_PER_REQUEST
    
  lambda:
    runtime: nodejs18.x
    memory: 256
    timeout: 30
    
  api_gateway:
    type: HTTP
    cors: true
    authorization: JWT
    
monitoring:
  dashboards:
    - C_N-Operations
    - C_N-Oracle-Status
  alarms:
    error_rate_threshold: 0.005
    latency_threshold_ms: 600
    dlq_threshold: 1
