name: 'continuum_overworld'
version: '0.1.0'
config-version: 2

profile: 'continuum_overworld'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  continuum_overworld:
    bronze:
      +materialized: incremental
      +unique_key: event_id
    silver:
      +materialized: table
    gold:
      +materialized: table

vars:
  # Project variables
  project_name: "Continuum_Overworld"
  lake_bucket: "lake"
  bronze_path: "bronze"
  silver_path: "silver"
  gold_path: "gold"

seeds:
  continuum_overworld:
    +quote_columns: false

dependencies:
  - package: dbt-labs/dbt_utils
    version: 1.1.1

macros:
  - macro: incremental_helpers