name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 2.1.0)'
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/C_N-GitHubDeployRole
          aws-region: us-east-1
      
      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ inputs.version }}" -m "Release v${{ inputs.version }}"
          git push origin "v${{ inputs.version }}"
      
      - name: Update SSM Version
        run: |
          aws ssm put-parameter \
            --name "/C_N/Config/Version" \
            --value "v${{ inputs.version }}" \
            --type String \
            --overwrite
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          body: |
            ## Continuum Nexus v${{ inputs.version }}
            
            ### Deployment
            - Environment: PROD
            - Region: us-east-1
            - Prefix: C_N
            
            ### Components
            - ✅ Infrastructure deployed
            - ✅ Lambda functions updated
            - ✅ Frontend synchronized
          draft: false
          prerelease: false